[package]
name = "obsidian_to_notion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.17"
chrono = "0.4"
tempfile = "3.7"